config/routes.rb
Rails.application.routes.draw do
  resources :pads do
    resources :tasks
  end
  resources :pads
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pad.rb
class Pad < ApplicationRecord
  belongs_to :user, foreign_key: "created_by_id"
  has_many :tasks
  validates :name, presence: true
end

app/controllers/pads_controller.rb
class PadsController < ApplicationController
  before_action :set_pad, only: [:show, :edit, :update, :destroy]

  # GET /pads
  # GET /pads.json
  def index
    @pads = Pad.all
    @pad = Pad.new
  end

  # GET /pads/1
  # GET /pads/1.json
  def show
    @task = Task.new
    @tasks = Task.where(pad_id: @pad.id)
  end

  # GET /pads/new
  def new
    @pad = Pad.new
  end

  # GET /pads/1/edit
  def edit
  end

  # POST /pads
  # POST /pads.json
  def create
    @pad = Pad.new(pad_params)

    respond_to do |format|
      if @pad.save
        format.html { redirect_to @pad, notice: 'Pad was successfully created.' }
        format.json { render :show, status: :created, location: @pad }
      else
        format.html { render :new }
        format.json { render json: @pad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pads/1
  # PATCH/PUT /pads/1.json
  def update
    respond_to do |format|
      if @pad.update(pad_params)
        format.html { redirect_to @pad, notice: 'Pad was successfully updated.' }
        format.json { render :show, status: :ok, location: @pad }
      else
        format.html { render :edit }
        format.json { render json: @pad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pads/1
  # DELETE /pads/1.json
  def destroy
    @pad.destroy
    respond_to do |format|
      format.html { redirect_to pads_url, notice: 'Pad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pad
      @pad = Pad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pad_params
      params.require(:pad).permit(:name, :description, :created_by_id)
    end
end

app/helpers/pads_helper.rb
module PadsHelper
end

app/views/pads/_form.html.erb
<div class="card">
  <h5 class="card-header">
    Editing Pad
  </h5>
  <div class="card-body">
<%= bootstrap_form_with(model: pad, local: true) do |form| %>
  <% if pad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pad.errors.count, "error") %> prohibited this pad from being saved:</h2>

      <ul>
      <% pad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.text_field :name %>
    <%= form.text_field :description %>
    <%= form.hidden_field :created_by_id, value: current_user.id %>
    <%= form.submit %>
  </div>
  <% end %>
  </div>
</div>

app/views/pads/_inline_task_form.html.erb
<div class="card">
  <h5 class="card-header">New Task</h5>
  <div class="card-body">
<%= bootstrap_form_for(@task, url: pad_tasks_path(@pad, @task)) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(t@ask.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :name %>
  <%= form.check_box :complete %>
  <%= form.hidden_field :created_by_id, value: current_user.id %>
  <%= form.hidden_field :pad_id, value: @pad.id %>
  <br>
  <%= form.submit %>
<% end %>
</div>
</div>

app/views/pads/_task_listing.html.erb
<div class="card">
  <h2 class="card-header">
    <%= @pad.name %>
    <%= link_to 'Edit', edit_pad_path(@pad), class: 'btn btn-primary float-right' %>
  <h2>
  <h5 class="card-body">
    <%= @pad.description %>
  </h5>
  <div class="card-body">
    <div class='table-responsive'>
      <table class='table table-striped'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Complete</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td><%= task.name %></td>
            <td><%= task.complete %></td>
            <td><%= link_to fa_icon("edit lg"), edit_pad_task_path(@pad,task) %></td>
            <td><%= link_to fa_icon("trash lg"), pad_task_path(@pad,task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/pads/edit.html.erb
<%= render 'form', pad: @pad %>

app/views/pads/index.html.erb
<div class="card">
  <h2 class="card-header">
    Pads
  </h2>
  <div class="card-body">
    <div class='table-responsive'>
      <table class='table table-striped'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @pads.each do |pad| %>
          <tr>
            <td><%= link_to pad.name, pad %></td>
            <td><%= pad.description %></td>
            <td><%= link_to fa_icon("edit lg"), edit_pad_path(pad) %></td>
            <td><%= link_to fa_icon("trash lg"), pad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>
<br>
<%= render 'form', pad: @pad %>
<%= link_to 'New Pad', new_pad_path %>

app/views/pads/new.html.erb
<h1>New Pad</h1>

<%= render 'form', pad: @pad %>

<%= link_to 'Back', pads_path %>

app/views/pads/show.html.erb
<br>
<%= render partial: 'inline_task_form' %>
<br>
<%= render partial: 'task_listing' %>
<br>